[package]
name = "uniq"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
bincode = "1.3.3"

[profile.release]
lto = true
codegen-units = 1
